# Generated by Django 5.0.13 on 2026-08-02 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
        ('idc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(max_length=255, verbose_name='请求路径')),
                ('status', models.IntegerField(verbose_name='响应状态码')),
                ('ip', models.CharField(blank=True, max_length=45, null=True, verbose_name='客户端 IP')),
                ('cost_ms', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='处理耗时(ms)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='请求时间')),
            ],
            options={
                'verbose_name': '请求耗时记录',
                'verbose_name_plural': '请求耗时记录',
                'db_table': 'request_log',
            },
        ),
        migrations.CreateModel(
            name='HostStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('city', '按城市'), ('idc', '按机房')], max_length=20, verbose_name='统计维度')),
                ('total_count', models.IntegerField(verbose_name='主机总数')),
                ('online_count', models.IntegerField(default=0, verbose_name='在线主机数')),
                ('offline_count', models.IntegerField(default=0, verbose_name='离线主机数')),
                ('stat_date', models.DateField(verbose_name='统计日期')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='写入时间')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='city.city', verbose_name='城市')),
                ('idc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='idc.idc', verbose_name='机房')),
            ],
            options={
                'verbose_name': '主机统计',
                'verbose_name_plural': '主机统计',
                'db_table': 'host_statistics',
            },
        ),
    ]
