# Generated by Django 5.0.13 on 2026-08-02 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddConstraint(
            model_name='hoststatistics',
            constraint=models.UniqueConstraint(fields=('dimension', 'city', 'idc', 'stat_date'), name='uniq_stat_dimension_city_idc_date'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['create_time'], name='request_log_create__bc9b83_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['method', 'path'], name='request_log_method_43f45c_idx'),
        ),
    ]
