# Generated by Django 5.0.13 on 2026-08-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '新增'), ('update', '更新'), ('delete', '删除')], max_length=50, verbose_name='操作类型')),
                ('resource', models.CharField(max_length=50, verbose_name='操作资源')),
                ('resource_id', models.BigIntegerField(blank=True, null=True, verbose_name='资源 ID')),
                ('detail', models.JSONField(blank=True, null=True, verbose_name='操作详情')),
                ('ip', models.CharField(blank=True, max_length=45, null=True, verbose_name='请求 IP')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_log',
            },
        ),
    ]
