# Generated by Django 5.0.13 on 2026-08-02 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['resource', 'resource_id'], name='operation_l_resourc_fea136_idx'),
        ),
    ]
