# Generated by Django 5.0.13 on 2026-08-02 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hostname', models.CharField(max_length=100, unique=True, verbose_name='主机名')),
                ('ip', models.CharField(max_length=45, unique=True, verbose_name='IP 地址')),
                ('port', models.PositiveSmallIntegerField(default=22, verbose_name='SSH 端口')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线')], default='offline', max_length=20, verbose_name='在线状态')),
                ('os_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作系统')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='idc.idc', verbose_name='所属机房')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
                'db_table': 'host',
            },
        ),
        migrations.CreateModel(
            name='HostPasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_password', models.BinaryField(max_length=512, verbose_name='加密后的密码')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否当前有效')),
                ('valid_from', models.DateTimeField(verbose_name='生效时间')),
                ('expire_at', models.DateTimeField(verbose_name='过期时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to='host.host', verbose_name='关联主机')),
            ],
            options={
                'verbose_name': '密码历史',
                'verbose_name_plural': '密码历史',
                'db_table': 'host_password_history',
            },
        ),
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['status'], name='host_status_980bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='hostpasswordhistory',
            index=models.Index(fields=['host', 'is_active'], name='host_passwo_host_id_20fae1_idx'),
        ),
    ]
