# Generated by Django 5.0.13 on 2026-08-02 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='机房名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='机房编码')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='机房地址')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idcs', to='city.city', verbose_name='所属城市')),
            ],
            options={
                'verbose_name': '机房',
                'verbose_name_plural': '机房',
                'db_table': 'idc',
            },
        ),
        migrations.AddConstraint(
            model_name='idc',
            constraint=models.UniqueConstraint(fields=('city', 'name'), name='uniq_city_idc_name'),
        ),
    ]
